src/DotNetDeployments/Models/Data/Solution.cs
public class Solution
{
    public int SolutionId { get; set; }
    public string SolutionName { get; set; }
}

src/DotNetDeployments/Models/ErrorViewModel.cs
using System;

namespace DotNetDeployments.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/DotNetDeployments/Controllers/DeploymentConfigurationController.cs
using Amazon.CodeDeploy;
using Amazon.CodeDeploy.Model;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace DotNetDeployments.Controllers
{
    public class DeploymentConfigurationController : Controller
    {
        IAmazonCodeDeploy AmazonCodeDeployClient { get; set; }

        public DeploymentConfigurationController(IAmazonCodeDeploy amazonCodeDeployClient)
        {
            AmazonCodeDeployClient = amazonCodeDeployClient;
        }
        
        public IActionResult AppNameForm()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AppNewSave(CreateApplicationRequest applicationRequest)
        {
            var createAppResponse = await AmazonCodeDeployClient.CreateApplicationAsync(applicationRequest);

            return View();
        }
    }
}

src/DotNetDeployments/Controllers/ProjectController.cs
using DotNetDeployments.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DotNetDeployments.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/DotNetDeployments/Views/DeploymentConfiguration/AppNameForm.cshtml
@model Amazon.CodeDeploy.Model.CreateApplicationRequest
@{ 
    ViewData["Title"] = "New Application Name";
}
<div class="row">
    <div class="col-xs-4">
        <h2>New Application Name</h2>
        @using (Html.BeginForm("AppNameSave", "Deployment", FormMethod.Post))
        {

            <div class="form-group">
                @Html.LabelFor(m => m.ApplicationName, "Application Name")
                @Html.TextBoxFor(m => m.ApplicationName, null, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary btn-lg" value="Add" />
            </div>

        }
    </div>
</div>

src/DotNetDeployments/Views/DeploymentConfiguration/Index.cshtml
@{
    ViewData["Title"] = "Deployment";
}

<div>
    <h1>Deployment Info</h1>    
</div>

src/DotNetDeployments/Views/Project/Index.cshtml
@{
    ViewData["Title"] = "Projects";
}

<h2>This view will include list of projects</h2>

src/DotNetDeployments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dot Net Deployments</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DotNetDeployments</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Project" asp-action="Index">Projects</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - DotNetDeployments</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>